<?php

$storefrontUrl = env('BROWSER_TEST_STOREFRONT_URL', 'http://browser-test.kneadit.test');

// Smoke tests for admin custom (non-resource) pages. Each test loads a
// pre-authenticated browser context via authenticatedVisit() and asserts
// the page's h1 heading is visible with no JavaScript errors.
//
// Prerequisite: BrowserTestFixtureSeeder has been run against the target
// tenant. The admin session file is auto-generated by authenticatedVisit()
// when missing or expired.

/**
 * @return list<array{0: string, 1: string}>
 */
dataset('admin_custom_pages', [
    'quick-order' => ['quick-order', 'Quick Order'],
    'manage-settings' => ['manage-settings', 'Manage Settings'],
    'referral-program' => ['referral-program', 'Referral Program'],
    'manage-page-content' => ['manage-page-content', 'Page Content'],
    'custom-domain' => ['custom-domain', 'Custom Domain'],
    'announcement-banner' => ['announcement-banner', 'Announcement Banner'],
    'homepage-builder' => ['homepage-builder', 'Homepage Builder'],
    'staff-management' => ['staff-management', 'Team Management'],
    'activity-log-page' => ['activity-log-page', 'Activity Log Page'],
    'baking-sheet' => ['baking-sheet', 'Baking Sheet'],
    'label-generator' => ['label-generator', 'Label Generator'],
]);

test('admin custom page renders cleanly', function (string $slug, string $heading) use ($storefrontUrl) {
    authenticatedVisit("{$storefrontUrl}/admin/{$slug}")
        ->assertSee($heading)
        ->assertNoJavaScriptErrors();
})->with('admin_custom_pages');
