<?php

use Illuminate\Support\Facades\Config;

$storefrontUrl = Config::string('browser-testing.storefront_url');

// Dashboard smoke test. The login flow test only checks the heading is visible
// immediately after redirect — it doesn't wait for widgets to poll and render,
// so widget-level errors (500s on Livewire update, cache-related crashes, etc.)
// can slip through. This test explicitly visits /admin post-auth and asserts
// zero JS errors after full page settlement.
//
// Prerequisite: BrowserTestFixtureSeeder has been run. The admin session
// file is auto-generated by authenticatedVisit() when missing or expired.

test('admin dashboard renders all widgets cleanly', function () use ($storefrontUrl) {
    authenticatedVisit("{$storefrontUrl}/admin")
        ->assertSee('Dashboard')
        ->assertNoJavaScriptErrors();
})->group('launch-smoke');
