<?php

use Illuminate\Support\Facades\Config;

$storefrontUrl = Config::string('browser-testing.storefront_url');

// Smoke tests for admin resource view (detail) pages. Uses fixture IDs
// captured by prepare-admin-session.py — no DB access needed from the test.
//
// Only two Filament resources in this panel expose a view page:
//   - orders  (admin/orders/{id})
//   - surveys (admin/surveys/{id})
//
// Other resources (products, customers, etc.) don't have dedicated view
// pages — they use inline modal actions instead.
//
// Prerequisite: BrowserTestFixtureSeeder has been run against the target
// tenant. The session + fixture-ids files are auto-generated by
// authenticatedVisit() / fixtureId() when missing or expired.

test('admin order view page renders cleanly', function () use ($storefrontUrl) {
    $id = fixtureId('review_order_id');

    authenticatedVisit("{$storefrontUrl}/admin/orders/{$id}")
        ->assertSee('BROWSER-TEST-REVIEW')
        ->assertNoJavaScriptErrors();
});

test('admin survey view page renders cleanly', function () use ($storefrontUrl) {
    $id = fixtureId('survey_id');

    authenticatedVisit("{$storefrontUrl}/admin/surveys/{$id}")
        ->assertSee('Browser Test Survey')
        ->assertNoJavaScriptErrors();
});
