<?php

$centralUrl = Illuminate\Support\Facades\Config::string('browser-testing.central_url');

// Smoke test for the landlord (central) admin dashboard. Uses the central
// admin storage state, which is auto-generated by authenticatedCentralVisit()
// when missing or expired.
//
// Prerequisite: php artisan db:seed --class="Database\Seeders\BrowserTestCentralFixtureSeeder"

test('central admin dashboard renders without JS errors', function () use ($centralUrl) {
    authenticatedCentralVisit("{$centralUrl}/admin")
        ->assertSee('Dashboard')
        ->assertNoJavaScriptErrors();
});
