<?php

use Illuminate\Support\Facades\Config;

$centralUrl = Config::string('browser-testing.central_url');

// Smoke tests for the landlord (central) admin panel — resource indexes and
// platform pages. Each test loads a pre-authenticated browser context via
// authenticatedCentralVisit() and asserts the h1 heading + no JS errors.
//
// Prerequisite: php artisan db:seed --class="Database\\Seeders\\BrowserTestCentralFixtureSeeder"
// The central admin session file is auto-generated by authenticatedCentralVisit()
// when missing or expired.

/**
 * @return list<array{0: string, 1: string}>
 */
dataset('central_admin_pages', [
    // Resources
    'tenants' => ['tenants', 'Tenants'],
    'blog-posts' => ['blog-posts', 'Blog Posts'],
    'support-tickets' => ['support-tickets', 'Support Tickets'],
    'email-campaigns' => ['email-campaigns', 'Email Campaigns'],
    'messages' => ['messages', 'Messages'],
    'announcements' => ['announcements', 'Platform Announcements'],
    'scheduled-checkins' => ['scheduled-checkins', 'Scheduled Checkins'],

    // Platform pages
    'activity' => ['activity', 'Activity'],
    'analytics' => ['analytics', 'Analytics'],
    'bakery-insights' => ['bakery-insights', 'Bakery Insights'],
    'tenant-comparison' => ['tenant-comparison', 'Bakery Comparison'],
    'feature-usage' => ['feature-usage', 'Feature Usage'],
    'data-export' => ['data-export', 'Data Export'],
    'maintenance-mode' => ['maintenance-mode', 'Maintenance Mode'],
    'onboarding-tracker' => ['onboarding-tracker', 'Onboarding Tracker'],
]);

test('central admin page renders cleanly', function (string $slug, string $heading) use ($centralUrl) {
    authenticatedCentralVisit("{$centralUrl}/admin/{$slug}")
        ->waitForEvent('networkidle')
        ->assertSee($heading)
        ->assertNoJavaScriptErrors();
})->with('central_admin_pages');
